#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

ENV_FILE=".env.development.local"
MODE="${AV_DESIGNER_SUPABASE_MODE:-auto}" # auto | local | remote

is_generated_env_file() {
  [[ -f "${1}" ]] || return 1
  local first_line
  first_line="$(head -n 1 "${1}" 2>/dev/null || true)"
  [[ "${first_line}" == *"generated by scripts/supabase-local.sh"* ]]
}

write_env_file() {
  local label="${1}"
  local api_url="${2}"
  local anon_key="${3}"
  local mailpit_url="${4:-}"

  cat > "${ENV_FILE}" <<EOF
# ${label} (generated by scripts/supabase-local.sh)
VITE_SUPABASE_URL="${api_url}"
VITE_SUPABASE_ANON_KEY="${anon_key}"
EOF

  if [[ -n "${mailpit_url}" ]]; then
    printf '\nVITE_SUPABASE_MAILPIT_URL="%s"\n' "${mailpit_url}" >> "${ENV_FILE}"
  fi
}

docker_running() {
  command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1
}

use_remote_env() {
  if [[ -f ".env.local" ]]; then
    set -a
    # shellcheck disable=SC1091
    source ".env.local"
    set +a

    if [[ -n "${VITE_SUPABASE_URL:-}" && -n "${VITE_SUPABASE_ANON_KEY:-}" ]]; then
      write_env_file "Remote Supabase (from .env.local)" "${VITE_SUPABASE_URL}" "${VITE_SUPABASE_ANON_KEY}"
      echo "Wrote ${ENV_FILE} pointing to remote Supabase (.env.local)."
      return 0
    fi

    echo "Found .env.local but it is missing VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY."
  else
    echo "Missing .env.local. Create it from .env.example to use a remote Supabase project."
  fi

  if is_generated_env_file "${ENV_FILE}"; then
    rm -f "${ENV_FILE}"
    echo "Removed generated ${ENV_FILE} to avoid stale Supabase settings."
  fi

  return 0
}

use_local_env() {
  if ! command -v supabase >/dev/null 2>&1; then
    echo "Supabase CLI not found. Install it to use local Supabase."
    return 1
  fi

  if ! docker_running; then
    echo "Docker is not running. Local Supabase requires Docker Desktop."
    return 1
  fi

  if ! supabase status >/dev/null 2>&1; then
    echo "Supabase is not running. Starting local Supabase..."
    if ! supabase start; then
      echo "Failed to start local Supabase."
      return 1
    fi
  fi

  echo "Applying local migrations..."
  if ! supabase db push --local --yes >/dev/null; then
    echo "Failed to apply local migrations to local Supabase."
    return 1
  fi

  local status_env
  if ! status_env="$(supabase status -o env 2>/dev/null)"; then
    echo "Failed to read Supabase local status variables."
    echo "Run: supabase status -o env"
    return 1
  fi

  local api_url anon_key mailpit_url
  api_url="$(
    printf '%s\n' "${status_env}" |
      awk -F= '$1=="API_URL"{gsub(/^"/,"",$2);gsub(/"$/,"",$2);print $2}'
  )"
  anon_key="$(
    printf '%s\n' "${status_env}" |
      awk -F= '$1=="ANON_KEY"{gsub(/^"/,"",$2);gsub(/"$/,"",$2);print $2}'
  )"
  mailpit_url="$(
    printf '%s\n' "${status_env}" |
      awk -F= '$1=="MAILPIT_URL"{gsub(/^"/,"",$2);gsub(/"$/,"",$2);print $2}'
  )"

  if [[ -z "${api_url}" || -z "${anon_key}" ]]; then
    echo "Failed to read Supabase local status variables."
    echo "Run: supabase status -o env"
    return 1
  fi

  write_env_file "Local Supabase" "${api_url}" "${anon_key}" "${mailpit_url}"

  echo "Wrote ${ENV_FILE} pointing to local Supabase."
  if [[ -n "${mailpit_url}" ]]; then
    echo "Auth emails are captured at: ${mailpit_url}"
  fi

  return 0
}

case "${MODE}" in
  local)
    use_local_env
    ;;
  remote)
    use_remote_env
    ;;
  auto)
    if use_local_env; then
      exit 0
    fi
    echo "Local Supabase unavailable; falling back to remote Supabase (.env.local)."
    use_remote_env
    ;;
  *)
    echo "Unknown AV_DESIGNER_SUPABASE_MODE: ${MODE} (expected: auto|local|remote)"
    exit 1
    ;;
esac
